---

- name: add yum repositories by url
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.url }}"
    gpgkey: "{{ item.gpgkey }}"
    mode: 0644
  loop: "{{ yum_repositories_urls }}"
  tags: yum-repositories

- name: add yum repositories by package
  yum:
    name: "{{ item }}"
  loop: "{{ yum_repositories_pkgs }}"
  tags: yum-repositories
